<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mgade-L440" name="com.deem.joltage.platformtests.test.UserProfileServiceTest" tests="21" failures="1" timestamp="20 Dec 2016 15:56:05 GMT" time="168.075" errors="1">
  <testcase name="updateUserServiceTest" time="14.603" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.deem.joltage.platformtests.test.UserProfileServiceTest.updateUserServiceTest(UserProfileServiceTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </error>
  </testcase> <!-- updateUserServiceTest -->
  <testcase name="validateUserInfoTest" time="1.174" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="GetHealthCheckServiceTest" time="0.874" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="GetAssignRolesServiceTest" time="17.074" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="GetAssignRolesServiceTest" time="15.532" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="validateBatchUsersInfoTest" time="0.856" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="createUserServiceTest" time="1.070" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="getApproverInfoTest" time="2.573" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="updateUserRoleServiceTest" time="15.216" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="validateUserInfoTest" time="2.426" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest">
    <failure type="java.lang.AssertionError" message="Given should be same expected [Mahesh] but found [mahesh]">
      <![CDATA[java.lang.AssertionError: Given should be same expected [Mahesh] but found [mahesh]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.deem.joltage.platformtests.test.UserProfileServiceTest.validateUserInfoTest(UserProfileServiceTest.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
    </failure>
  </testcase> <!-- validateUserInfoTest -->
  <testcase name="createBatchUsersTest" time="1.007" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="removeApproverChainTest" time="15.111" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="removeApproverChainTest" time="15.191" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="GetApproverChainServiceTest" time="1.141" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="updateBatchUsersTest" time="0.906" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="removeApproverChainTest" time="14.749" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="updateUserRoleServiceTest" time="15.214" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="removeApproverChainTest" time="15.154" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="getApproverInfoTest" time="2.364" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="removeApproverChainTest" time="14.628" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
  <testcase name="validateUserInfoTest" time="1.212" classname="com.deem.joltage.platformtests.test.UserProfileServiceTest"/>
</testsuite> <!-- com.deem.joltage.platformtests.test.UserProfileServiceTest -->
